// Do not edit. This file is machine generated by the Resource DLL Wizard.

library pryDispatchMp3Files;

{ITE} {DFMFileType} {DispatchMp3File.dfm}
{ITE} {DFMFileType} {PlayMp3File.dfm}
{ITE} {RCFileType} {Win32\Debug\pryDispatchMp3Files_DRC.rc}

{$R 'DispatchMp3File.dfm' 'Mp3Lstfrm:TForm'}
{$R 'PlayMp3File.dfm' 'PlayMp3Music:TForm'}
{$R 'Win32\Debug\pryDispatchMp3Files_DRC.res' 'Win32\Debug\pryDispatchMp3Files_DRC.rc'}

{$E KOR}

begin
end.
